# Generated by Django 2.1.1 on 2018-09-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='field_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='content.Location'),
        ),
    ]
