# Generated by Django 2.1.1 on 2018-10-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('inspiration', models.TextField()),
                ('outcomes', models.TextField()),
                ('procedure', models.TextField()),
                ('exit_expectations', models.TextField()),
                ('finish_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lesson', to='lessons.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(null=True, upload_to='')),
                ('attribution', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_lesson', to='lessons.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('criteria', models.CharField(max_length=1000)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_lesson', to='lessons.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(to='lessons.Tag'),
        ),
    ]
