# Generated by Django 2.1.1 on 2018-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.TextField(default='Testing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='rubric',
            field=models.TextField(default='Testing'),
            preserve_default=False,
        ),
    ]
